name: HTML

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "* */3 * * *"

jobs:
  everything:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.4.1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
      - name: HTML Proofer
        uses: chabad360/htmlproofer@master
        with:
          directory: "/"
          # The directory to scan
          arguments: --allow-missing-href
          # The arguments to pass to HTMLProofer
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2.2.1

