name: Test site for publicly known js vulnerabilities

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "* */3 * * *"

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Test for public javascript library vulnerabilities 
        uses: lirantal/is-website-vulnerable@master
        with:
          scan-url: "https://yoursite.com"
